"""Pipecat STT adapter for the existing Whisper HTTP transcription contract."""

from __future__ import annotations

from datetime import datetime, timezone
from typing import AsyncGenerator

import httpx
from pipecat.frames.frames import Frame, TranscriptionFrame
from pipecat.services.stt_service import SegmentedSTTService

from src.core.config import settings
from src.core.logger import logger

MIN_ANSWER_SECONDS = 0.25


class WhisperHttpSTTService(SegmentedSTTService):
    """Transcribe finalized audio segments using the existing Whisper endpoint."""

    def __init__(self, *, sample_rate: int = 24000):
        super().__init__(audio_passthrough=False, sample_rate=sample_rate)

    @property
    def wants_wav_segments(self) -> bool:
        """Whisper receives a WAV upload generated by SegmentedSTTService."""
        return True

    async def run_stt(self, audio: bytes) -> AsyncGenerator[Frame | None, None]:
        # Do not discard short, valid screening answers such as "yes", a
        # technology name, or a concise clarification. Pipecat appends trailing
        # silence to completed segments, so this only filters near-empty noise.
        sample_rate = self.sample_rate or self._init_sample_rate or 16000
        min_bytes = int(sample_rate * 2 * MIN_ANSWER_SECONDS)
        if len(audio) < min_bytes:
            logger.info(
                "Ignoring near-empty candidate audio segment",
                extra={"audio_bytes": len(audio), "minimum_bytes": min_bytes},
            )
            return

        headers = {"Authorization": f"Bearer {settings.whisper_api_key}"}
        files = {"file": ("audio.wav", audio, "audio/wav")}
        data = {
            "model": "whisper-large-v3",
            "response_format": "json",
            "language": "en",
        }

        try:
            async with httpx.AsyncClient(timeout=10.0) as client:
                response = await client.post(
                    settings.whisper_api_url
                    or "https://api.groq.com/openai/v1/audio/transcriptions",
                    files=files,
                    data=data,
                    headers=headers,
                )
                response.raise_for_status()
                transcript = response.json().get("text", "").strip()
        except Exception as error:
            logger.error("Pipecat Whisper transcription failed", extra={"error": str(error)})
            return

        if transcript:
            yield TranscriptionFrame(
                text=transcript,
                user_id="candidate",
                timestamp=datetime.now(timezone.utc).isoformat(),
                finalized=True,
            )
