# Generated by Django 5.1.2 on 2025-10-15 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_organization_is_async_transcription_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='is_managed_zoom_oauth_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
