/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        // Primary CTA / brand action — strong cobalt
        primary: '#2b7fd4',
        'on-primary': '#ffffff',
        'primary-container': '#d9ebfc',
        'on-primary-container': '#0b3d74',
        'primary-fixed': '#d9ebfc',
        'primary-fixed-dim': '#a8d0fa',
        'on-primary-fixed': '#0b3d74',
        // Hover / pressed primary
        'on-primary-fixed-variant': '#1a5fad',
        'inverse-primary': '#a8d0fa',
        // Links, focus, nav accent — same family as primary
        secondary: '#2b7fd4',
        'on-secondary': '#ffffff',
        'secondary-container': '#b8d9fa',
        'on-secondary-container': '#0b3d74',
        'secondary-fixed': '#d9ebfc',
        'secondary-fixed-dim': '#a8d0fa',
        'on-secondary-fixed': '#0b3d74',
        'on-secondary-fixed-variant': '#1a5fad',
        // Soft sky accent (decorative / light fills)
        tertiary: '#4a9cf5',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#e3f1fc',
        'on-tertiary-container': '#0b3d74',
        // Cool white / ice-blue surfaces
        surface: '#f4f9ff',
        'surface-bright': '#fafcfe',
        'surface-dim': '#d6e6f5',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#eef5fc',
        'surface-container': '#e5f0fa',
        'surface-container-high': '#dceaf8',
        'surface-container-highest': '#d0e3f5',
        'surface-variant': '#dceaf8',
        // Deep navy text
        'on-surface': '#0f2740',
        'on-surface-variant': '#4a647a',
        'on-background': '#0f2740',
        background: '#f4f9ff',
        outline: '#8aa7bf',
        'outline-variant': '#c5d8ea',
        'surface-tint': '#2b7fd4',
        'inverse-surface': '#16304a',
        'inverse-on-surface': '#eef5fc',
        // Status (badges / alerts only)
        success: '#065F46',
        'success-container': '#D1FAE5',
        'on-success-container': '#065F46',
        warning: '#92400E',
        'warning-container': '#FEF3C7',
        'on-warning-container': '#92400E',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        'margin-mobile': '16px',
        gutter: '20px',
        xs: '4px',
        xl: '32px',
        sm: '8px',
        '2xl': '48px',
        base: '4px',
        lg: '24px',
        'margin-desktop': '32px',
        md: '16px',
        'sidebar-width': '260px',
      },
      fontFamily: {
        'body-sm': ['Inter', 'system-ui', 'sans-serif'],
        'body-md': ['Inter', 'system-ui', 'sans-serif'],
        'body-lg': ['Inter', 'system-ui', 'sans-serif'],
        'label-md': ['Geist', 'Inter', 'system-ui', 'sans-serif'],
        'display-lg': ['Geist', 'Inter', 'system-ui', 'sans-serif'],
        'display-lg-mobile': ['Geist', 'Inter', 'system-ui', 'sans-serif'],
        'headline-sm': ['Geist', 'Inter', 'system-ui', 'sans-serif'],
        'headline-md': ['Geist', 'Inter', 'system-ui', 'sans-serif'],
        'mono-sm': ['Geist', 'Inter', 'system-ui', 'sans-serif'],
        sans: ['Inter', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'label-md': [
          '12px',
          { lineHeight: '16px', letterSpacing: '0.02em', fontWeight: '500' },
        ],
        'display-lg': [
          '36px',
          { lineHeight: '44px', letterSpacing: '-0.02em', fontWeight: '600' },
        ],
        'display-lg-mobile': [
          '28px',
          { lineHeight: '34px', letterSpacing: '-0.02em', fontWeight: '600' },
        ],
        'headline-sm': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'headline-md': [
          '24px',
          { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '600' },
        ],
        'mono-sm': ['13px', { lineHeight: '18px', fontWeight: '400' }],
      },
    },
  },
  plugins: [],
}
