"""initial_schema

Revision ID: c478691b4383
Revises: 
Create Date: 2026-08-11 14:33:04.892440

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c478691b4383'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=True),
    sa.Column('logo_url', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_organizations_is_active', 'organizations', ['is_active'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('role', sa.Enum('super_admin', 'organization_admin', 'hr', 'candidate', name='user_role'), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Enum('active', 'inactive', 'suspended', name='user_status'), server_default='active', nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index('ix_users_organization_id', 'users', ['organization_id'], unique=False)
    op.create_index('ix_users_role', 'users', ['role'], unique=False)
    op.create_index('ix_users_status', 'users', ['status'], unique=False)
    op.create_table('job_descriptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('job_type', sa.Enum('part_time', 'full_time', 'contract', name='job_type'), nullable=True),
    sa.Column('work_type', sa.Enum('onsite', 'hybrid', 'remote', name='work_type'), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('experience_min', sa.Integer(), nullable=True),
    sa.Column('experience_max', sa.Integer(), nullable=True),
    sa.Column('skills', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'published', 'closed', name='job_status'), server_default='draft', nullable=False),
    sa.Column('parsed_jd', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_job_descriptions_organization_id', 'job_descriptions', ['organization_id'], unique=False)
    op.create_index('ix_job_descriptions_parsed_jd', 'job_descriptions', ['parsed_jd'], unique=False, postgresql_using='gin')
    op.create_index('ix_job_descriptions_status', 'job_descriptions', ['status'], unique=False)
    op.create_table('applications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_description_id', sa.UUID(), nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('resume_url', sa.String(length=1024), nullable=True),
    sa.Column('parsed_resume', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('candidate_yoe', sa.Float(), nullable=True),
    sa.Column('resume_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('job_fit_analysis', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Enum('applied', 'interview_scheduled', 'interview_completed', 'shortlist_for_l1', 'rejected', name='application_status'), server_default='applied', nullable=False),
    sa.Column('applied_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_description_id'], ['job_descriptions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_description_id', 'candidate_id', name='uq_applications_job_candidate')
    )
    op.create_index('ix_applications_candidate_yoe', 'applications', ['candidate_yoe'], unique=False)
    op.create_index('ix_applications_job_description_id', 'applications', ['job_description_id'], unique=False)
    op.create_index('ix_applications_job_status_score', 'applications', ['job_description_id', 'status', 'resume_score'], unique=False)
    op.create_index('ix_applications_parsed_resume', 'applications', ['parsed_resume'], unique=False, postgresql_using='gin')
    op.create_index('ix_applications_resume_score', 'applications', ['resume_score'], unique=False)
    op.create_index('ix_applications_status', 'applications', ['status'], unique=False)
    op.create_table('interview_session',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('scheduled_by', sa.UUID(), nullable=False),
    sa.Column('interview_type', sa.Enum('screening_ai', name='interview_type'), server_default='screening_ai', nullable=False),
    sa.Column('status', sa.Enum('scheduled', 'rescheduled', 'completed', 'no_show', 'cancelled', 'failed', name='interview_status'), server_default='scheduled', nullable=False),
    sa.Column('interview_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('comment', sa.String(length=500), nullable=True),
    sa.Column('generated_questions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scheduled_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_interview_session_application_id', 'interview_session', ['application_id'], unique=False)
    op.create_index('ix_interview_session_status', 'interview_session', ['status'], unique=False)
    op.create_table('interview_analysis',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('interview_session_id', sa.UUID(), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('analysis_result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('question_answer', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('recording_url', sa.Text(), nullable=True),
    # Reuse existing interview_type enum (created with interview_session)
    sa.Column(
        'interview_type',
        postgresql.ENUM('screening_ai', name='interview_type', create_type=False),
        nullable=True,
    ),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['interview_session_id'], ['interview_session.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('interview_session_id')
    )
    op.create_index('ix_interview_analysis_application_id', 'interview_analysis', ['application_id'], unique=False)
    op.create_table(
        'refresh_token_revocations',
        sa.Column('jti', sa.String(length=36), nullable=False),
        sa.Column('user_id', sa.UUID(), nullable=False),
        sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint('jti'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('refresh_token_revocations')
    op.drop_index('ix_interview_analysis_application_id', table_name='interview_analysis')
    op.drop_table('interview_analysis')
    op.drop_index('ix_interview_session_status', table_name='interview_session')
    op.drop_index('ix_interview_session_application_id', table_name='interview_session')
    op.drop_table('interview_session')
    op.drop_index('ix_applications_status', table_name='applications')
    op.drop_index('ix_applications_resume_score', table_name='applications')
    op.drop_index('ix_applications_parsed_resume', table_name='applications', postgresql_using='gin')
    op.drop_index('ix_applications_job_status_score', table_name='applications')
    op.drop_index('ix_applications_job_description_id', table_name='applications')
    op.drop_index('ix_applications_candidate_yoe', table_name='applications')
    op.drop_table('applications')
    op.drop_index('ix_job_descriptions_status', table_name='job_descriptions')
    op.drop_index('ix_job_descriptions_parsed_jd', table_name='job_descriptions', postgresql_using='gin')
    op.drop_index('ix_job_descriptions_organization_id', table_name='job_descriptions')
    op.drop_table('job_descriptions')
    op.drop_index('ix_users_status', table_name='users')
    op.drop_index('ix_users_role', table_name='users')
    op.drop_index('ix_users_organization_id', table_name='users')
    op.drop_table('users')
    op.drop_index('ix_organizations_is_active', table_name='organizations')
    op.drop_table('organizations')

    # Drop enum types created by the upgrade
    sa.Enum(name='application_status').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='interview_status').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='interview_type').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='job_status').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='job_type').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='work_type').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='user_status').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='user_role').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
