# Generated by Django 5.1.2 on 2025-10-16 16:26

import concurrency.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0058_alter_webhookdeliveryattempt_webhook_trigger_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webhookdeliveryattempt',
            name='webhook_trigger_type',
            field=models.IntegerField(choices=[(1, 'Bot State Change'), (2, 'Transcript Update'), (3, 'Chat Messages Update'), (4, 'Participant Join/Leave'), (5, 'Calendar Events Update'), (6, 'Calendar State Change'), (7, 'Async Transcription State Change'), (8, 'Zoom OAuth Connection State Change')], default=1),
        ),
        migrations.CreateModel(
            name='ZoomOAuthApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.CharField(editable=False, max_length=32, unique=True)),
                ('_encrypted_data', models.BinaryField(null=True)),
                ('client_id', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_verified_webhook_received_at', models.DateTimeField(blank=True, null=True)),
                ('last_unverified_webhook_received_at', models.DateTimeField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zoom_oauth_apps', to='bots.project')),
            ],
        ),
        migrations.CreateModel(
            name='ZoomOAuthConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.CharField(editable=False, max_length=32, unique=True)),
                ('state', models.IntegerField(choices=[(1, 'Connected'), (2, 'Disconnected')], default=1)),
                ('connection_failure_data', models.JSONField(default=None, null=True)),
                ('user_id', models.CharField(max_length=255)),
                ('account_id', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', concurrency.fields.IntegerVersionField(default=0, help_text='record revision number')),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('last_attempted_sync_at', models.DateTimeField(blank=True, null=True)),
                ('last_successful_sync_at', models.DateTimeField(blank=True, null=True)),
                ('last_successful_sync_started_at', models.DateTimeField(blank=True, null=True)),
                ('sync_task_enqueued_at', models.DateTimeField(blank=True, null=True)),
                ('sync_task_requested_at', models.DateTimeField(blank=True, null=True)),
                ('_encrypted_data', models.BinaryField(null=True)),
                ('zoom_oauth_app', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='zoom_oauth_connections', to='bots.zoomoauthapp')),
            ],
        ),
        migrations.CreateModel(
            name='ZoomMeetingToZoomOAuthConnectionMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.CharField(editable=False, max_length=32, unique=True)),
                ('meeting_id', models.CharField(max_length=25)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('zoom_oauth_app', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='zoom_meeting_to_zoom_oauth_connection_mappings', to='bots.zoomoauthapp')),
                ('zoom_oauth_connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zoom_meeting_to_zoom_oauth_connection_mappings', to='bots.zoomoauthconnection')),
            ],
        ),
        migrations.AddField(
            model_name='webhookdeliveryattempt',
            name='zoom_oauth_connection',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhook_delivery_attempts', to='bots.zoomoauthconnection'),
        ),
        migrations.AddConstraint(
            model_name='zoomoauthconnection',
            constraint=models.UniqueConstraint(fields=('zoom_oauth_app', 'user_id'), name='unique_zoom_oauth_connection_user_id'),
        ),
        migrations.AddIndex(
            model_name='zoommeetingtozoomoauthconnectionmapping',
            index=models.Index(fields=['meeting_id'], name='zoom_meeting_meeting_id_idx'),
        ),
        migrations.AddIndex(
            model_name='zoommeetingtozoomoauthconnectionmapping',
            index=models.Index(fields=['zoom_oauth_connection_id'], name='zm_zac_id_idx'),
        ),
        migrations.AddConstraint(
            model_name='zoommeetingtozoomoauthconnectionmapping',
            constraint=models.UniqueConstraint(fields=('zoom_oauth_app', 'meeting_id'), name='unique_zoom_meeting_id_zoom_oauth_app_id'),
        ),
    ]
