# Generated by Django 5.1.2 on 2025-10-28 03:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0059_alter_webhookdeliveryattempt_webhook_trigger_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleMeetBotLoginGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.CharField(editable=False, max_length=32, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='google_meet_bot_login_groups', to='bots.project')),
            ],
        ),
        migrations.CreateModel(
            name='GoogleMeetBotLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.CharField(editable=False, max_length=32, unique=True)),
                ('_encrypted_data', models.BinaryField(null=True)),
                ('workspace_domain', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='google_meet_bot_logins', to='bots.googlemeetbotlogingroup')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('group', 'email'), name='unique_google_meet_bot_login_email')],
            },
        ),
    ]
