# Generated by Django 5.1.2 on 2025-11-13 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0060_googlemeetbotlogingroup_googlemeetbotlogin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participantevent',
            name='event_type',
            field=models.IntegerField(choices=[(1, 'Join'), (2, 'Leave'), (5, 'Update')]),
        ),
    ]
