# Generated by Django 5.1.2 on 2025-11-17 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0061_alter_participantevent_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credentials',
            name='credential_type',
            field=models.IntegerField(choices=[(1, 'Deepgram'), (2, 'Zoom OAuth'), (3, 'Google Text To Speech'), (4, 'Gladia'), (5, 'OpenAI'), (6, 'Assembly AI'), (7, 'Sarvam'), (8, 'Teams Bot Login'), (9, 'External Media Storage'), (10, 'ElevenLabs'), (11, 'Kyutai')]),
        ),
        migrations.AlterField(
            model_name='recording',
            name='transcription_provider',
            field=models.IntegerField(blank=True, choices=[(1, 'Deepgram'), (2, 'Closed Caption From Platform'), (3, 'Gladia'), (4, 'OpenAI'), (5, 'Assembly AI'), (6, 'Sarvam'), (7, 'ElevenLabs'), (8, 'Kyutai')], null=True),
        ),
    ]
