# Generated by Django 5.1.14 on 2026-05-04 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0081_remove_botevent_valid_event_type_event_sub_type_combinations_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotLoginGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.CharField(editable=False, max_length=32, unique=True)),
                ('platform', models.CharField(choices=[('google_meet', 'Google Meet'), ('teams', 'Teams')], max_length=32)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bot_login_groups', to='bots.project')),
            ],
        ),
        migrations.CreateModel(
            name='BotLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.CharField(editable=False, max_length=32, unique=True)),
                ('_encrypted_data', models.BinaryField(null=True)),
                ('workspace_domain', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bot_logins', to='bots.botlogingroup')),
            ],
        ),
        migrations.AddConstraint(
            model_name='botlogingroup',
            constraint=models.UniqueConstraint(fields=('project', 'platform', 'name'), name='unique_bot_login_group_project_platform_name'),
        ),
        migrations.AddConstraint(
            model_name='botlogin',
            constraint=models.UniqueConstraint(fields=('group', 'email'), name='unique_bot_login_email'),
        ),
    ]
