# Generated by Django 5.1.14 on 2026-05-04 15:52

import json
import secrets
import string
from collections import defaultdict

from cryptography.fernet import Fernet
from django.conf import settings
from django.db import migrations


GOOGLE_MEET_PLATFORM = "google_meet"
TEAMS_PLATFORM = "teams"

# Matches Credentials.CredentialTypes.TEAMS_BOT_LOGIN, which is being deprecated
# in favor of BotLogin.
TEAMS_BOT_LOGIN_CREDENTIAL_TYPE = 8

NEW_GROUP_OBJECT_ID_PREFIX = "blg_"
NEW_LOGIN_OBJECT_ID_PREFIX = "bl_"


def _remap_object_id(legacy_object_id, new_prefix):
    # Reuse the random suffix from the legacy object_id so the new row is
    # trivially traceable back to the deprecated row it was migrated from.
    _, _, suffix = legacy_object_id.partition("_")
    return f"{new_prefix}{suffix}"


def _generate_object_id(prefix):
    random_string = "".join(secrets.choice(string.ascii_letters + string.digits) for _ in range(16))
    return f"{prefix}{random_string}"


def populate_bot_login_groups_from_deprecated_models(apps, schema_editor):
    GoogleMeetBotLoginGroup = apps.get_model('bots', 'GoogleMeetBotLoginGroup')
    BotLoginGroup = apps.get_model('bots', 'BotLoginGroup')
    BotLogin = apps.get_model('bots', 'BotLogin')
    Credentials = apps.get_model('bots', 'Credentials')

    legacy_groups = GoogleMeetBotLoginGroup.objects.all().order_by('project_id', 'created_at', 'id')

    # The new (BotLoginGroup, BotLogin) tables are introduced in 0082, so they're
    # empty at this point. A simple per-project counter is enough to satisfy the
    # (project, platform, name) unique constraint.
    per_project_meet_index = defaultdict(lambda: 1)
    per_project_teams_index = defaultdict(lambda: 1)

    meet_groups_migrated = 0
    meet_logins_migrated = 0
    teams_groups_migrated = 0
    teams_credentials_skipped = 0

    for legacy_group in legacy_groups:
        project_id = legacy_group.project_id
        name = f"Meet login group {per_project_meet_index[project_id]}"
        per_project_meet_index[project_id] += 1

        new_group = BotLoginGroup.objects.create(
            project_id=project_id,
            object_id=_remap_object_id(legacy_group.object_id, NEW_GROUP_OBJECT_ID_PREFIX),
            platform=GOOGLE_MEET_PLATFORM,
            name=name,
        )
        meet_groups_migrated += 1

        for legacy_login in legacy_group.google_meet_bot_logins.all():
            BotLogin.objects.create(
                group=new_group,
                object_id=_remap_object_id(legacy_login.object_id, NEW_LOGIN_OBJECT_ID_PREFIX),
                _encrypted_data=legacy_login._encrypted_data,
                workspace_domain=legacy_login.workspace_domain,
                email=legacy_login.email,
                is_active=legacy_login.is_active,
                last_used_at=legacy_login.last_used_at,
            )
            meet_logins_migrated += 1

    print(f"Migrated {meet_groups_migrated} Google Meet bot login group(s) and {meet_logins_migrated} bot login(s).")

    # Backfill legacy Teams bot login credentials, which were stored as a
    # project-scoped Credentials row of type TEAMS_BOT_LOGIN. The encrypted
    # payload contained {"username": <email>, "password": <password>}; in the
    # new schema the email lives on BotLogin.email and only {"password": ...}
    # remains encrypted on BotLogin._encrypted_data.
    fernet = Fernet(settings.CREDENTIALS_ENCRYPTION_KEY)
    teams_credentials = (
        Credentials.objects
        .filter(credential_type=TEAMS_BOT_LOGIN_CREDENTIAL_TYPE)
        .order_by('project_id', 'created_at', 'id')
    )

    for credential in teams_credentials:
        if not credential._encrypted_data:
            continue

        try:
            decrypted = json.loads(fernet.decrypt(bytes(credential._encrypted_data)).decode())
        except Exception as exc:
            # If the payload can't be decrypted (e.g. it was encrypted with a
            # rotated key that's no longer available), just skip this row
            # rather than failing the entire migration.
            print(f"Skipping Teams credential id={credential.id} (project_id={credential.project_id}) due to decrypt failure: {repr(exc)}")
            teams_credentials_skipped += 1
            continue
        email = (decrypted.get("username") or "").strip()
        password = decrypted.get("password")
        if not email or not password:
            teams_credentials_skipped += 1
            continue

        project_id = credential.project_id
        group_name = f"Teams login group {per_project_teams_index[project_id]}"
        per_project_teams_index[project_id] += 1

        new_group = BotLoginGroup.objects.create(
            project_id=project_id,
            object_id=_generate_object_id(NEW_GROUP_OBJECT_ID_PREFIX),
            platform=TEAMS_PLATFORM,
            name=group_name,
        )

        BotLogin.objects.create(
            group=new_group,
            object_id=_generate_object_id(NEW_LOGIN_OBJECT_ID_PREFIX),
            _encrypted_data=fernet.encrypt(json.dumps({"password": password}).encode()),
            email=email,
        )
        teams_groups_migrated += 1

    print(f"Migrated {teams_groups_migrated} Teams bot login group(s); skipped {teams_credentials_skipped} legacy Teams credential(s).")


def reverse_populate_bot_login_groups_from_deprecated_models(apps, schema_editor):
    # No reverse operation - we don't want to delete created BotLoginGroups / BotLogins.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0082_botlogingroup_botlogin_and_more'),
    ]

    operations = [
        migrations.RunPython(
            populate_bot_login_groups_from_deprecated_models,
            reverse_populate_bot_login_groups_from_deprecated_models,
        ),
    ]
