# Generated by Django 5.1.14 on 2026-05-28 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0085_alter_recording_transcription_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='meeting_url',
            field=models.CharField(max_length=2048),
        ),
        migrations.AlterField(
            model_name='calendarevent',
            name='meeting_url',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='webhooksubscription',
            name='url',
            field=models.URLField(max_length=2048),
        ),
    ]
