# Generated by Django 5.1.14 on 2026-06-30 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0086_alter_bot_meeting_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='concurrent_bots_limit_override',
            field=models.IntegerField(blank=True, help_text='Per-project concurrent bots limit. If null, the global CONCURRENT_BOTS_LIMIT setting is used.', null=True),
        ),
    ]
